name: Issue Report
description: Report an issue
labels: [issue]
body:
  - type: input
    attributes:
      label: OS Version
      description: OS version of the system issue is observed on
      placeholder: macOS 14.0 (Sonoma)
    validations:
      required: true
      
  - type: input
    attributes:
      label: OS Version
      description: Spotify application version
      placeholder: 1.2.22.982.g794acc0a
    validations:
      required: true

  - type: input
    attributes:
      label: OS Version
      description: Spicetify version
      placeholder: 1.2.42
    validations:
      required: true

  - type: textarea
    attributes:
      label: Description
      description: Please explain the observed behavior and why it's an issue
    validations:
      required: true
